[package]
name = "tbe"
version = "0.1.0"
authors = ["Sergey Shandar"]
description = "Truncated Binary Encoding"
license = "Apache-2.0"
repository = "https://github.com/rust-common/tbe"

[dependencies]
base2 = "0.2.2"
int = "0.2.10"
bitrw = "0.6.0"
