[package]
name = "tbe"
version = "0.3.2"
authors = ["Sergey Shandar"]
description = "Truncated Binary Encoding"
license = "Apache-2.0"
repository = "https://github.com/rust-common/tbe"

[dependencies]
base2 = "0.3.0"
int = "0.3.0"
bitrw = "0.8.2"
